### ISSUE TITLE
undetected_chromedriver

### ISSUE THREAD

**Issue by Yogabayu** [MRHRTZ/Shopee-flashsale-bot#10]
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 6, in <module>
    import undetected_chromedriver as uc
ModuleNotFoundError: No module named 'undetected_chromedriver'

saat run python main.py

**Comment by MRHRTZ** [comment]
Coba install module nya
`pip install undetected-chromedriver`

**Comment by imkiddo** [comment]
hi,
I experieced same issue. 
Installed  that module
However the problem still persists 


Traceback (most recent call last):
  File "/Users/kiddo/Shopee-flashsale-bot/main.py", line 13, in <module>
    from lib.definitions import initProgram, checkChromeDriver, menu
  File "/Users/kiddo/Shopee-flashsale-bot/lib/definitions.py", line 14, in <module>
    from lib.driverExecutor import executeScript
  File "/Users/kiddo/Shopee-flashsale-bot/lib/driverExecutor.py", line 6, in <module>
    from seleniumwire.undetected_chromedriver import v2 as webdriver
  File "/Users/kiddo/Library/Python/3.9/lib/python/site-packages/seleniumwire/undetected_chromedriver/__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "/Users/kiddo/Library/Python/3.9/lib/python/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 8, in <module>
    raise ImportError(
ImportError: undetected_chromedriver not found. Install it with `pip install undetected_chromedriver`.

**Comment by MRHRTZ** [comment]
[5fa5414](https://github.com/MRHRTZ/Shopee-flashsale-bot/commit/5fa541417acd58b8cd6a124976c8b373f6d4354e) check new commit
