### ISSUE TITLE
 Message: invalid cookie domain

### ISSUE THREAD

**Issue by akim7fold** [MRHRTZ/Shopee-flashsale-bot#11]
[ Initial chrome automation ... ]
Traceback (most recent call last):
  File "C:\Users\Akem\Documents\Shopee-flashsale-bot-master\main.py", line 16, in <module>
    menu()
  File "C:\Users\Akem\Documents\Shopee-flashsale-bot-master\lib\definitions.py", line 184, in menu
    start_countdown()
  File "C:\Users\Akem\Documents\Shopee-flashsale-bot-master\lib\definitions.py", line 294, in start_countdown
    executeScript(**settings)
  File "C:\Users\Akem\Documents\Shopee-flashsale-bot-master\lib\driverExecutor.py", line 89, in executeScript
    driver.add_cookie(cookie)
  File "C:\Users\Akem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 633, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "C:\Users\Akem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Akem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain
  (Session info: chrome=115.0.5790.102)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00E5A813+48355]
        (No symbol) [0x00DEC4B1]
        (No symbol) [0x00CF5220]
        (No symbol) [0x00D593D3]
        (No symbol) [0x00D3A73C]
        (No symbol) [0x00D4C922]
        (No symbol) [0x00D3A536]
        (No symbol) [0x00D182DC]
        (No symbol) [0x00D193DD]
        GetHandleVerifier [0x010BAABD+2539405]
        GetHandleVerifier [0x010FA78F+2800735]
        GetHandleVerifier [0x010F456C+2775612]
        GetHandleVerifier [0x00EE51E0+616112]
        (No symbol) [0x00DF5F8C]
        (No symbol) [0x00DF2328]
        (No symbol) [0x00DF240B]
        (No symbol) [0x00DE4FF7]
        BaseThreadInitThunk [0x771E7D59+25]
        RtlInitializeExceptionChain [0x77D5B79B+107]
        RtlClearBits [0x77D5B71F+191]

**Comment by MRHRTZ** [comment]
Explain in advance this error appears after doing what, and send screenshot of your session json if u made it.
