### ISSUE TITLE
error when click start countdown

### ISSUE THREAD

**Issue by pocopocox3** [MRHRTZ/Shopee-flashsale-bot#13]
DevTools listening on ws://127.0.0.1:63445/devtools/browser/5d811603-91ec-4a65-ad57-4e7c253fd3b3
[17912:9488:0811/103741.530:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for accounts.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103741.770:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for shopee.co.id failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:7028:0811/103741.770:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for shopee.co.id failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103742.733:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for deo.shopeemobile.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103743.385:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for www.googletagmanager.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103744.182:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for www.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103744.221:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for connect.facebook.net failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103744.558:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for o468184.ingest.sentry.io failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103744.612:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for dem.shopee.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103744.793:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for googleads.g.doubleclick.net failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103745.621:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for www.facebook.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[13372:15960:0811/103746.360:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[17912:9488:0811/103747.018:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for www.google-analytics.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103747.020:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for 9469210.fls.doubleclick.net failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103747.073:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for content-autofill.googleapis.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103747.198:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for df.infra.sz.shopee.co.id failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103747.892:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for ampcid.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103748.057:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for endpoint.mms.shopee.co.id failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103748.073:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for adservice.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103748.074:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for c-api-bit.shopeemobile.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103748.460:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for analytics.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[17912:9488:0811/103748.464:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for stats.g.doubleclick.net failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

[13372:15960:0811/103750.616:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[17912:9488:0811/103751.122:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for down-id.img.susercontent.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found

Traceback (most recent call last):
  File "C:\Users\nurul\OneDrive\Desktop\Shopee-flashsale-bot-master\main.py", line 16, in <module>
    menu()
  File "C:\Users\nurul\OneDrive\Desktop\Shopee-flashsale-bot-master\lib\definitions.py", line 184, in menu
    start_countdown()
  File "C:\Users\nurul\OneDrive\Desktop\Shopee-flashsale-bot-master\lib\definitions.py", line 294, in start_countdown
    executeScript(**settings)
  File "C:\Users\nurul\OneDrive\Desktop\Shopee-flashsale-bot-master\lib\driverExecutor.py", line 85, in executeScript
    session = json.load(f)
              ^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MRHRTZ** [comment]
The error comes from loading the session, did you include valid json in the session file?
